/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   signal_handler.c                                   :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: dgutak <dgutak@student.42vienna.com>       +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2023/11/04 12:53:04 by vfrants           #+#    #+#             */
/*   Updated: 2023/11/07 15:03:55 by dgutak           ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "minishell.h"
#include <signal.h>

int		g_signal = 0;

/**
 * The function "handler" is used to handle the SIGINT signal, typically generated by pressing Ctrl+C,
 * and performs some actions when the signal is received.
 * 
 * @param status The parameter "status" is an integer that represents the status of the signal that
 * triggered the handler function. In this case, the function is checking if the status is equal to
 * SIGINT, which is the signal sent when the user presses Ctrl+C in the terminal.
 */
void	handler(int status)
{
	if (status == SIGINT)
	{
		g_signal = CNTRL_C;
		write(STDERR_FILENO, "\n", 1);
		rl_on_new_line();
		rl_replace_line("", 0);
		rl_redisplay();
	}
}

/**
 * The function "handler_heredoc" handles the SIGINT signal by setting a global variable and performing
 * some input/output operations.
 * 
 * @param status The parameter "status" is the status code of the signal that triggered the handler. In
 * this case, the handler is checking if the status code is equal to SIGINT, which represents the
 * interrupt signal (usually triggered by pressing Ctrl+C in the terminal).
 */
void	handler_heredoc(int status)
{
	if (status == SIGINT)
	{
		g_signal = CNTRL_C;
		ioctl(STDIN_FILENO, TIOCSTI, "\n");
		rl_replace_line("", 0);
		rl_on_new_line();

	}
}

/**
 * The function `setup_signals` sets up signal handlers based on the mode specified in the `data`
 * structure.
 * 
 * @param data The "data" parameter is a pointer to a structure of type "t_data".
 */
void	setup_signals(t_data *data)
{
	if (data->mode == INTERACTIVE)
	{
		signal(SIGINT, &handler);
		signal(SIGQUIT, SIG_IGN);
	}
	else if (data->mode == NON_INTERACTIVE)
	{
		signal(SIGINT, SIG_IGN);
		signal(SIGQUIT, SIG_IGN);
	}
	else if (data->mode == CHILD)
	{
		signal(SIGINT, SIG_DFL);
		signal(SIGQUIT, SIG_DFL);
	}
	else if (data->mode == HEREDOC)
	{
		signal(SIGINT, &handler_heredoc);
		signal(SIGQUIT, SIG_IGN);
	}
}

/**
 * The function "mode" sets the mode of a data structure and sets up signals.
 * 
 * @param data A pointer to a structure of type t_data.
 * @param mode The mode parameter is of type t_mode, which is likely a custom data type defined
 * elsewhere in the code.
 */
void	mode(t_data *data, t_mode mode)
{
	data->mode = mode;
	setup_signals(data);
}
